/*
 * NOTE: This file is auto-generated by cjc.
 * Do NOT modify it manually.
 */
package demo;

import demo.Base;
import static cangjie.lang.LibraryLoader.loadLibrary;
import cangjie.lang.internal.$$NativeConstructorMarker;

public class Calc extends Base {
    static {
        loadLibrary("staticuser");
    }

    private long $rid;

    public Calc() {
        super();
        initCJObject();
    }

    private Calc($$NativeConstructorMarker __init__) {
        super();
    }

    private final native void initCJObject();

    public static final int add(int a, int b) {
        return addii(a, b);
    }

    private static final native int addii(int a, int b);

    private final native void deleteCJObject(long $rid);

    @Override
    protected void finalize() {
        deleteCJObject(this.$rid);
    }
}
