/*
 * NOTE: This file is auto-generated by cjc.
 * Do NOT modify it manually.
 */
package demo;

import demo.Base;
import static cangjie.lang.LibraryLoader.loadLibrary;
import cangjie.lang.internal.$$NativeConstructorMarker;

public class Child extends Base {
    static {
        loadLibrary("impluser");
    }

    private long $rid;

    public Child() {
        super();
        initCJObject();
    }

    private Child($$NativeConstructorMarker __init__) {
        super();
    }

    private final native void initCJObject();

    public final int ping(int n) {
        return pingi(this.$rid, n);
    }

    private final native int pingi(long $rid, int n);

    private final native void deleteCJObject(long $rid);

    @Override
    protected void finalize() {
        deleteCJObject(this.$rid);
    }
}
