/*
 * NOTE: This file is auto-generated by cjc.
 * Do NOT modify it manually.
 */
package demo;

import demo.Base;
import static cangjie.lang.LibraryLoader.loadLibrary;
import cangjie.lang.internal.$$NativeConstructorMarker;

public class Counter extends Base {
    static {
        loadLibrary("propuser");
    }

    private long $rid;

    public final int getCount() {
        return getCountImpl(this.$rid);
    }

    private final native int getCountImpl(long $rid);

    public final void setCount(int count) {
        setCountImpl(this.$rid, count);
    }

    private final native void setCountImpl(long $rid, int count);

    public Counter() {
        super();
        initCJObject();
    }

    private Counter($$NativeConstructorMarker __init__) {
        super();
    }

    private final native void initCJObject();

    private final native void deleteCJObject(long $rid);

    @Override
    protected void finalize() {
        deleteCJObject(this.$rid);
    }
}
