[package]
  cjc-version = "1.1.0"
  name = "frontend_tool"
  organization = "cjcj"
  description = "Self-hosted Cangjie compiler FrontendTool module scaffold"
  version = "0.1.0"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  "cjcj::basic" = { path = "../basic" }
  "cjcj::codegen" = { path = "../codegen" }
  "cjcj::frontend" = { path = "../frontend" }
  "cjcj::incremental_compilation" = { path = "../incremental_compilation" }
  "cjcj::option" = { path = "../option" }
  "cjcj::utils" = { path = "../utils" }
