[package]
  cjc-version = "1.1.0"
  name = "cjc"
  organization = "cangjie_compiler"
  description = "Self-hosted Cangjie compiler executable entry"
  version = "0.1.0"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "executable"
  compile-option = ""
  override-compile-option = ""
  link-option = "/root/cj_build/wt/fix_llvmshim_domloop/runtime_shim/cjselfhost_llvmshim.o /root/.cjv/toolchains/nightly-1.2.0-alpha.20260619020029/third_party/llvm/lib/libLLVM-15.so -lstdc++ -rpath /root/.cjv/toolchains/nightly-1.2.0-alpha.20260619020029/third_party/llvm/lib"
  package-configuration = {}

[dependencies]
  "cangjie_compiler::driver" = { path = "../driver" }
  "cangjie_compiler::utils" = { path = "../utils" }
  "cangjie_compiler::frontend" = { path = "../frontend" }
  "cangjie_compiler::chir" = { path = "../chir" }
  "cangjie_compiler::basic" = { path = "../basic" }
