[package]
  cjc-version = "1.1.0"
  name = "modules"
  organization = "cjcj"
  description = "Self-hosted Cangjie compiler Modules module scaffold"
  version = "0.1.0"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  "cjcj::ast" = { path = "../ast" }
  "cjcj::basic" = { path = "../basic" }
  "cjcj::flatbuffers" = { path = "../flatbuffers" }
  "cjcj::lex" = { path = "../lex" }
  "cjcj::option" = { path = "../option" }
  "cjcj::utils" = { path = "../utils" }
