[package]
  cjc-version = "1.1.0"
  name = "compiler_unittest"
  organization = "cjcj"
  description = "Downstream compiler unittest harness package"
  version = "0.1.0"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = "runtime_shim/cjselfhost_llvmshim.o /root/.cjv/toolchains/nightly-1.2.0-alpha.20260619020029/third_party/llvm/lib/libLLVM-15.so -lstdc++ -rpath /root/.cjv/toolchains/nightly-1.2.0-alpha.20260619020029/third_party/llvm/lib"
  package-configuration = {}

[dependencies]
  "cjcj::ast" = { path = "../ast" }
  "cjcj::basic" = { path = "../basic" }
  "cjcj::codegen" = { path = "../codegen" }
  "cjcj::driver" = { path = "../driver" }
  "cjcj::frontend" = { path = "../frontend" }
  "cjcj::lex" = { path = "../lex" }
  "cjcj::macro_pkg" = { path = "../macro" }
  "cjcj::option" = { path = "../option" }
  "cjcj::parse" = { path = "../parse" }
  "cjcj::sema" = { path = "../sema" }
  "cjcj::utils" = { path = "../utils" }
