[package]
  cjc-version = "1.1.0"
  name = "codegen"
  organization = "cjcj"
  description = "Self-hosted Cangjie compiler CodeGen module scaffold"
  version = "0.1.0"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  "cjcj::basic" = { path = "../basic" }
  "cjcj::chir" = { path = "../chir" }
  "cjcj::mangle" = { path = "../mangle" }
  "cjcj::option" = { path = "../option" }
  "cjcj::utils" = { path = "../utils" }
