[package]
  cjc-version = "1.1.0"
  name = "frontend"
  organization = "cangjie_compiler"
  description = "Self-hosted Cangjie compiler Frontend module scaffold"
  version = "0.1.0"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  "cangjie_compiler::basic" = { path = "../basic" }
  "cangjie_compiler::chir" = { path = "../chir" }
  "cangjie_compiler::codegen" = { path = "../codegen" }
  "cangjie_compiler::lex" = { path = "../lex" }
  "cangjie_compiler::option" = { path = "../option" }
  "cangjie_compiler::utils" = { path = "../utils" }
