[package]
  cjc-version = "1.1.0"
  name = "frontend"
  organization = "cangjie_compiler"
  description = "Self-hosted Cangjie compiler Frontend module scaffold"
  version = "0.1.0"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  "cangjie_compiler::ast" = { path = "../ast" }
  "cangjie_compiler::basic" = { path = "../basic" }
  "cangjie_compiler::chir" = { path = "../chir" }
  "cangjie_compiler::codegen" = { path = "../codegen" }
  "cangjie_compiler::conditional_compilation" = { path = "../conditional_compilation" }
  "cangjie_compiler::lex" = { path = "../lex" }
  "cangjie_compiler::macro_pkg" = { path = "../macro" }
  "cangjie_compiler::mangle" = { path = "../mangle" }
  "cangjie_compiler::meta_transformation" = { path = "../meta_transformation" }
  "cangjie_compiler::modules" = { path = "../modules" }
  "cangjie_compiler::option" = { path = "../option" }
  "cangjie_compiler::parse" = { path = "../parse" }
  "cangjie_compiler::sema" = { path = "../sema" }
  "cangjie_compiler::utils" = { path = "../utils" }
