#!/usr/bin/env bash
# Complete the unchanged runtime gate with independent build/language SDKs.
set -euo pipefail
ulimit -c 0
build_sdk_mode=0
if [[ ${1:-} == --build-sdk ]]; then
  build_sdk_mode=1
  shift
fi
source_root=$(realpath "${1:?runtime checkout}")
if [[ $build_sdk_mode == 1 ]]; then
  build_sdk=$(realpath "${2:?pipeline build SDK}")
else
  tuple=$(realpath "${2:?verified tuple}")
fi
active=$(realpath -m "${3:?new private SDK directory}")
installed=$(realpath "${4:?runtime install root}")
repo=$(cd "$(dirname "$0")/../.." && pwd)
pin="$repo/ci/h48_language_tuple_pin.json"

# Select the build that produced the installed SO, then let its own resolver
# validate both published files. No other configuration may satisfy the gate.
installed_sha=$(sha256sum "$installed/runtime/lib/linux_x86_64_cjnative/libcangjie-runtime.so" | cut -d' ' -f1)
manifests=()
for manifest in "$source_root"/runtime/output/temp/*/runtime-build-config.txt; do
  [[ -f "$manifest" ]] || continue
  if [[ $(sed -n 's/^RUNTIME_SHA256=//p' "$manifest") == "$installed_sha" ]]; then
    manifests+=("$manifest")
  fi
done
if [[ ${#manifests[@]} != 1 ]]; then
  echo "COLOUR_RT_GATE_BUILD_IDENTITY count=${#manifests[@]}" >&2
  exit 2
fi
manifest=${manifests[0]}
export GCV2_RUNTIME_CONFIG
GCV2_RUNTIME_CONFIG=$(sed -n 's/^CONFIG_ID=//p' "$manifest")
target=$(bash "$source_root/runtime/build/resolve_runtime_output.sh" "$source_root/runtime" "$GCV2_RUNTIME_CONFIG")
if [[ $build_sdk_mode == 0 ]]; then
python3 "$repo/ci/release/language_tuple.py" activate \
  --root "$tuple" --manifest-sha256 "$(jq -r .manifest_sha256 "$pin")" \
  --compiler-sha256 "$(jq -r .compiler_sha256 "$pin")" \
  --target "$target" --target-runtime-sha256 "$installed_sha" \
  --target-boundscheck-sha256 "$(sed -n 's/^BOUNDSCHECK_SHA256=//p' "$manifest")" \
  --output "$active" > "$active.env"
# Generated by language_tuple.py activate for this private SDK.
# shellcheck source=/dev/null
source "$active.env"
build_sdk="$active/sdk"
fi
# LANGUAGE_TOOLCHAIN.md:37-43: only the build SDK must contain this target.
# The qualified language SDK retains its original runtime and SDK.lock.json.
cmp "$target/libcangjie-runtime.so" "$build_sdk/runtime/lib/linux_x86_64_cjnative/libcangjie-runtime.so"
cmp "$target/libboundscheck.so" "$build_sdk/runtime/lib/linux_x86_64_cjnative/libboundscheck.so"
language_inputs="$active-language"
if [[ -e "$language_inputs" ]]; then
  echo "COLOUR_RT_LANGUAGE_DEST_EXISTS $language_inputs" >&2
  exit 2
fi
node "$repo/ci/release/download_pinned.mjs" cjcj-dev/cjcj 1504 "$language_inputs"
export GC_UNIT_BUILD_SDK="$build_sdk"
export GC_UNIT_LANGUAGE_SDK="$language_inputs/sdk"
export GC_UNIT_CJC_RUNTIME_LIB_DIR="$GC_UNIT_LANGUAGE_SDK/host/compiler"
export GC_UNIT_LANGUAGE_QUALIFICATION="$source_root/runtime/tests/gc_unit/language_toolchain_qualification.json"
export GC_UNIT_COLOUR_CHECKER="$repo/ci/bootstrap/std_runtime_colour.py"
export GC_UNIT_COLOUR_HOST_RUNTIME="$GC_UNIT_CJC_RUNTIME_LIB_DIR/libcangjie-runtime.so"
export CANGJIE_HOME="$build_sdk" CJC="$GC_UNIT_LANGUAGE_SDK/bin/cjc"
export GCV2_RUNTIME_LIB_DIR="$target"
export GC_UNIT_GATE_LANGUAGE_TESTS=all
# This is the original complete gate, including its C++ cache qualification and
# language result assertions; deferred status alone never reaches packaging.
bash "$source_root/runtime/tests/gc_unit/gate_gc_unit.sh"
