#!/usr/bin/env bash
# Complete the unchanged runtime gate with the published language inputs.
set -euo pipefail
ulimit -c 0
source_root=$(realpath "${1:?runtime checkout}")
tuple=$(realpath "${2:?verified tuple}")
active=$(realpath -m "${3:?new private SDK directory}")
installed=$(realpath "${4:?runtime install root}")
build_sdk=$(realpath "${5:?SDK selected for the runtime build}")
repo=$(cd "$(dirname "$0")/../.." && pwd)
pin="$repo/ci/h48_language_tuple_pin.json"

# Select the build that produced the installed SO, then let its own resolver
# validate both published files. No other configuration may satisfy the gate.
installed_sha=$(sha256sum "$installed/runtime/lib/linux_x86_64_cjnative/libcangjie-runtime.so" | cut -d' ' -f1)
manifests=()
for manifest in "$source_root"/runtime/output/temp/*/runtime-build-config.txt; do
  [[ -f "$manifest" ]] || continue
  if [[ $(sed -n 's/^RUNTIME_SHA256=//p' "$manifest") == "$installed_sha" ]]; then
    manifests+=("$manifest")
  fi
done
if [[ ${#manifests[@]} != 1 ]]; then
  echo "COLOUR_RT_GATE_BUILD_IDENTITY count=${#manifests[@]}" >&2
  exit 2
fi
manifest=${manifests[0]}
export GCV2_RUNTIME_CONFIG
GCV2_RUNTIME_CONFIG=$(sed -n 's/^CONFIG_ID=//p' "$manifest")
target=$(bash "$source_root/runtime/build/resolve_runtime_output.sh" "$source_root/runtime" "$GCV2_RUNTIME_CONFIG")
python3 "$repo/ci/release/language_tuple.py" activate \
  --root "$tuple" --manifest-sha256 "$(jq -r .manifest_sha256 "$pin")" \
  --compiler-sha256 "$(jq -r .compiler_sha256 "$pin")" \
  --target "$target" --target-runtime-sha256 "$installed_sha" \
  --target-boundscheck-sha256 "$(sed -n 's/^BOUNDSCHECK_SHA256=//p' "$manifest")" \
  --output "$active" > "$active.env"
# Generated by language_tuple.py activate for this private SDK.
# shellcheck source=/dev/null
source "$active.env"
cp "$source_root/runtime/tests/gc_unit/language_toolchain_qualification.json" "$active/qualification.json"
cp "$repo/ci/bootstrap/std_runtime_colour.py" "$active/std_runtime_colour.py"
cp "$tuple/host/runtime/lib/linux_x86_64_cjnative/libcangjie-runtime.so" "$active/colour-host-runtime.so"
export GC_UNIT_BUILD_SDK="$build_sdk"
export GC_UNIT_LANGUAGE_SDK="$active/sdk"
export GC_UNIT_LANGUAGE_QUALIFICATION="$active/qualification.json"
export GC_UNIT_COLOUR_CHECKER="$active/std_runtime_colour.py"
export GC_UNIT_COLOUR_HOST_RUNTIME="$active/colour-host-runtime.so"
# activate already exports GC_UNIT_CJC_RUNTIME_LIB_DIR and GCV2_RUNTIME_LIB_DIR:
# the separate compiler host and this build's resolved target pair.
export GC_UNIT_GATE_LANGUAGE_TESTS=all
# setup_sdk records the official host SDK on PATH, LD_LIBRARY_PATH and
# cjHeapSize. Admission uses the explicit directories above. The complete
# gate re-runs the C++ suite, so that SDK search path must not reach it.
unset LD_LIBRARY_PATH
unset cjHeapSize
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# This is the original complete gate, including its C++ cache qualification and
# language result assertions; deferred status alone never reaches packaging.
printf ' ' >> "$GC_UNIT_LANGUAGE_QUALIFICATION"; bash "$source_root/runtime/tests/gc_unit/gate_gc_unit.sh"
