#!/usr/bin/env bash
# Complete the unchanged runtime gate with its same-source bootstrap SDK.
set -euo pipefail
ulimit -c 0
same_source=0
if [[ ${1:-} == --same-source ]]; then
  same_source=1
  shift
fi
source_root=$(realpath "${1:?runtime checkout}")
if [[ $same_source == 1 ]]; then
  sdk=$(realpath "${2:?same-source target SDK}")
  host=$(realpath "${3:?compiler host runtime directory}")
  std=$(realpath "${5:?bootstrap std install}")
else
  tuple=$(realpath "${2:?verified tuple}")
  active=$(realpath -m "${3:?new private SDK directory}")
fi
installed=$(realpath "${4:?runtime install root}")
repo=$(cd "$(dirname "$0")/../.." && pwd)
pin="$repo/ci/h48_language_tuple_pin.json"

# Select the build that produced the installed SO, then let its own resolver
# validate both published files. No other configuration may satisfy the gate.
installed_sha=$(sha256sum "$installed/runtime/lib/linux_x86_64_cjnative/libcangjie-runtime.so" | cut -d' ' -f1)
manifests=()
for manifest in "$source_root"/runtime/output/temp/*/runtime-build-config.txt; do
  [[ -f "$manifest" ]] || continue
  if [[ $(sed -n 's/^RUNTIME_SHA256=//p' "$manifest") == "$installed_sha" ]]; then
    manifests+=("$manifest")
  fi
done
if [[ ${#manifests[@]} != 1 ]]; then
  echo "COLOUR_RT_GATE_BUILD_IDENTITY count=${#manifests[@]}" >&2
  exit 2
fi
manifest=${manifests[0]}
export GCV2_RUNTIME_CONFIG
GCV2_RUNTIME_CONFIG=$(sed -n 's/^CONFIG_ID=//p' "$manifest")
target=$(bash "$source_root/runtime/build/resolve_runtime_output.sh" "$source_root/runtime" "$GCV2_RUNTIME_CONFIG")
if [[ $same_source == 1 ]]; then
  # sdk_build/sdk_verify produced this SDK in the supplied-stage1 entry. Bind
  # its actual installed std and runtime to the artifacts selected by the gate.
  for directory in lib/linux_x86_64_cjnative modules/linux_x86_64_cjnative runtime/lib/linux_x86_64_cjnative; do
    while IFS= read -r -d '' file; do
      cmp "$file" "$sdk/${file#"$std/"}"
    done < <(find "$std/$directory" -maxdepth 1 -type f \( -name 'libcangjie-std-*' -o -name 'std.*.cjo' \) -print0)
  done
  cmp "$std/lib/linux_x86_64_cjnative/libcangjie-std-core.a" "$sdk/lib/linux_x86_64_cjnative/libcangjie-std-core.a"
  cmp "$target/libcangjie-runtime.so" "$sdk/runtime/lib/linux_x86_64_cjnative/libcangjie-runtime.so"
  cmp "$target/libboundscheck.so" "$sdk/runtime/lib/linux_x86_64_cjnative/libboundscheck.so"
  test -f "$sdk/SDK.lock.json"
  export CANGJIE_HOME="$sdk" CJC="$sdk/bin/cjc"
  export GC_UNIT_CJC_RUNTIME_LIB_DIR="$host" GCV2_RUNTIME_LIB_DIR="$target"
else
python3 "$repo/ci/release/language_tuple.py" activate \
  --root "$tuple" --manifest-sha256 "$(jq -r .manifest_sha256 "$pin")" \
  --compiler-sha256 "$(jq -r .compiler_sha256 "$pin")" \
  --target "$target" --target-runtime-sha256 "$installed_sha" \
  --target-boundscheck-sha256 "$(sed -n 's/^BOUNDSCHECK_SHA256=//p' "$manifest")" \
  --output "$active" > "$active.env"
# Generated by language_tuple.py activate for this private SDK.
# shellcheck source=/dev/null
source "$active.env"
fi
export GC_UNIT_GATE_LANGUAGE_TESTS=all
# This is the original complete gate, including its C++ cache qualification and
# language result assertions; deferred status alone never reaches packaging.
bash "$source_root/runtime/tests/gc_unit/gate_gc_unit.sh"
