#!/usr/bin/env zx

import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {spawnSync} from 'node:child_process';
import {createHash} from 'node:crypto';

// Optional integration inputs: registered.def --raw-def raw.def --dll runtime.dll.
// These are generated by runtime's selector; this test has no selection rules.
const suppliedDefinition = argv._[0];
const temporaryRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'guardlist-'));
const failures = [];
let cases = 0;
const imports = ['dbghelp.dll', 'kernel32.dll', 'libboundscheck.dll', 'msvcrt.dll', 'ws2_32.dll'];
const namesFromDefinition = (text) => text.split(/\r?\n/)
  .map((line) => line.trim().match(/^(\S+)\s+@\d+(?:\s+DATA)?$/)?.[1]).filter(Boolean);
const hash = (bytes) => createHash('sha256').update(bytes).digest('hex');

try {
  const expectedDefinition = path.join(temporaryRoot, 'windows_x86_64_exports.def');
  const definition = suppliedDefinition ? await fs.readFile(path.resolve(suppliedDefinition), 'utf8')
    : 'EXPORTS\n    CJ_MCC_NewObject @1\n    CJ_MRT_GetThread @2\n';
  await fs.writeFile(expectedDefinition, definition);
  const expected = namesFromDefinition(definition);
  if (!expected.length) throw new Error('test requires a nonempty generated contract');
  const raw = argv['raw-def'] ? namesFromDefinition(await fs.readFile(argv['raw-def'], 'utf8')) : expected;
  console.log(`SELFTEST_INPUT contract=${expected.length} raw=${raw.length} contract_sha256=${hash(definition)}`);
  const runtimeDll = path.join(temporaryRoot, 'libcangjie-runtime.dll');
  const fakeObjdump = path.join(temporaryRoot, 'fake-objdump.mjs');
  const dumpFile = path.join(temporaryRoot, 'objdump.txt');
  await fs.writeFile(runtimeDll, 'offline fixture\n');
  await fs.writeFile(fakeObjdump, '#!/usr/bin/env node\nimport fs from "node:fs";\nprocess.stdout.write(fs.readFileSync(process.env.FAKE_DUMP_FILE));\n');
  await fs.chmod(fakeObjdump, 0o755);
  const guard = path.join(import.meta.dirname, 'verify_windows_runtime_exports.mjs');
  const invoke = (native = false, extraArgs = []) => spawnSync(
    process.env.ZX || 'npx',
    [...(process.env.ZX ? [] : ['--yes', 'zx@8']), guard, runtimeDll, '--expected-def', expectedDefinition, ...extraArgs],
    {encoding: 'utf8', env: {...process.env, OBJDUMP: native ? (process.env.OBJDUMP || 'objdump') : fakeObjdump,
      FAKE_DUMP_FILE: dumpFile}, maxBuffer: 64 * 1024 * 1024},
  );
  const check = (name, result, rc, errors = []) => {
    cases++;
    const actualErrors = result.stderr.trim().split(/\r?\n/).filter(Boolean);
    const ok = result.status === rc && JSON.stringify(actualErrors) === JSON.stringify(errors);
    console.log(`SELFTEST_CASE=${name} rc=${result.status} ASSERT=${ok ? 'PASS' : 'FAIL'}`);
    if (!ok) {
      failures.push(name);
      console.error(`SELFTEST_FAILURE=${name} expected_rc=${rc} expected_errors=${JSON.stringify(errors)}\n${result.stdout}${result.stderr}`);
    }
  };
  const run = async (name, names, rc, errors = [], dllImports = imports) => {
    await fs.writeFile(dumpFile, [...dllImports.map((dll) => `DLL Name: ${dll}`), '',
      '[Ordinal/Name Pointer] Table', ...names.map((symbol, index) => `  [${index}] ${symbol}`), '', ''].join('\n'));
    check(name, invoke(), rc, errors);
  };
  await run('contract-only-no-manual-implementation-list', expected, 0);
  await run('raw-extra-implementation-exports', raw, 0);
  for (const tag of ['220107', '220108']) {
    // Change only fixture implementation names, never contract names.
    const abiNames = raw.map((name) => expected.includes(name) ? name : name.replaceAll('220108', tag));
    abiNames.push(`_ZNSt3__17fixtureB9nqn${tag}Ev`);
    await run(`implementation-abi-${tag}`, abiNames, 0);
  }
  for (const symbol of expected) {
    await run(`missing:${symbol}`, raw.filter((name) => name !== symbol), 1, [`FATAL: missing exports: ${symbol}`]);
  }
  await run('equal-count-replacement', [...expected.slice(1), 'CJ_MCC_GuardlistReplacement'], 1,
    [`FATAL: missing exports: ${expected[0]}`]);
  await run('unexpected-import', raw, 1, ['FATAL: unexpected imports: unexpected.dll'], [...imports, 'unexpected.dll']);
  await run('missing-import', raw, 1, ['FATAL: missing official imports: dbghelp.dll'], imports.slice(1));
  await run('case-insensitive-imports', raw, 0, [], imports.map((name) => name.toUpperCase()));

  if (argv.dll) {
    const dll = await fs.readFile(argv.dll);
    console.log(`SELFTEST_NATIVE dll_sha256=${hash(dll)}`);
    await fs.writeFile(runtimeDll, dll);
    check('native-dll', invoke(true), 0);
    // Resolve PE export-name RVAs so each mutation changes an actual DLL export,
    // not a debug string or a synthetic objdump response.
    const pe = dll.readUInt32LE(0x3c);
    const optional = pe + 24;
    const sections = optional + dll.readUInt16LE(pe + 20);
    const rvaOffset = (rva) => {
      for (let i = 0; i < dll.readUInt16LE(pe + 6); i++) {
        const section = sections + i * 40;
        const start = dll.readUInt32LE(section + 12);
        if (rva >= start && rva < start + dll.readUInt32LE(section + 16)) {
          return dll.readUInt32LE(section + 20) + rva - start;
        }
      }
      throw new Error(`unmapped PE RVA ${rva}`);
    };
    if (dll.readUInt16LE(optional) !== 0x20b) throw new Error('native input must be PE32+');
    const exports = rvaOffset(dll.readUInt32LE(optional + 112));
    const names = rvaOffset(dll.readUInt32LE(exports + 32));
    const offsets = new Map();
    for (let i = 0; i < dll.readUInt32LE(exports + 24); i++) {
      const offset = rvaOffset(dll.readUInt32LE(names + i * 4));
      offsets.set(dll.toString('utf8', offset, dll.indexOf(0, offset)), offset);
    }
    // Sequential within this arm: every case reuses the same private DLL path.
    for (const symbol of expected) {
      const offset = offsets.get(symbol);
      if (offset === undefined) throw new Error(`native input lacks ${symbol}`);
      const changed = Buffer.from(dll);
      changed[offset] = '?'.charCodeAt(0);
      await fs.writeFile(runtimeDll, changed);
      check(`native-missing:${symbol}`, invoke(true), 1, [`FATAL: missing exports: ${symbol}`]);
    }
    // Give one noncontract implementation export two different ABI tags.
    // Reuse its PE name storage; neither variant touches a caller-contract name.
    const abiTemplate = '_ZNSt3__17fixtureB9nqn220108Ev';
    const implementation = [...offsets].find(([name]) =>
      !expected.includes(name) && name.length >= abiTemplate.length);
    if (!implementation) throw new Error('native ABI control requires an implementation export');
    for (const tag of ['220107', '220108']) {
      const changed = Buffer.from(dll);
      changed.write(abiTemplate.replace('220108', tag) + '\0', implementation[1]);
      await fs.writeFile(runtimeDll, changed);
      console.log(`SELFTEST_NATIVE_ABI tag=${tag} replaced=${implementation[0]} sha256=${hash(changed)}`);
      check(`native-abi-${tag}`, invoke(true), 0);
    }
  }
  console.log(`SELFTEST_RESULT=${failures.length ? 'FAIL' : 'PASS'} cases=${cases} failures=${failures.length}`);
  if (failures.length) process.exitCode = 1;
} finally {
  await fs.rm(temporaryRoot, {recursive: true, force: true});
}
