#!/usr/bin/env python3
"""Transcribe the runtime-validated LLVM contract; never infer C++ layout."""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess
import sys

FIELDS = ('typeInfoName type flag fieldNum instanceSize gctib uuid align typeArgsNum '
          'validInheritNum fieldOffsets sourceGeneric typeArgs fields superTypeInfo '
          'vExtensionDataStart mTableDesc reflectInfo').split()
GLOBALS = ('ObjectHeaderSize', 'ArrayLengthOffset', 'ArrayHeaderSize', 'TypeInfoSize')
ROOT = Path(__file__).resolve().parent.parent


def pin(file, name):
    return dict(line.split('=', 1) for line in (ROOT / 'ci' / file).read_text().splitlines()
                if re.match(r'^[A-Z_]+=', line))[name]


def render(header):
    values = {}
    namespace = None
    for line in header.decode().splitlines():
        if line == 'namespace TypeInfo {':
            namespace = 'TypeInfo'
        elif line == '} // namespace TypeInfo':
            namespace = None
        elif line.startswith('constexpr'):
            match = re.fullmatch(r'constexpr unsigned (\w+) = (\d+);', line)
            if not match:
                raise ValueError(f'unrecognized layout declaration: {line}')
            name, value = match.groups()
            key = (namespace, name)
            if key in values:
                raise ValueError(f'duplicate layout constant: {key}')
            values[key] = int(value)
    required = [(None, n) for n in GLOBALS]
    required += [('TypeInfo', f + suffix) for f in FIELDS for suffix in ('Index', 'Offset')]
    missing = [name for name in required if name not in values]
    if missing:
        raise ValueError(f'missing layout constants: {missing}')
    unknown = [k for k in values if k[0] == 'TypeInfo' and k not in required]
    if unknown:
        raise ValueError(f'unrecognized TypeInfo fields: {unknown}')
    indices = [values['TypeInfo', f + 'Index'] for f in FIELDS]
    if sorted(indices) != list(range(len(FIELDS))):
        raise ValueError(f'TypeInfo indices are not a complete unique field set: {indices}')
    lines = ['// Generated by ci/generate-codegen-runtime-layout.py; do not edit.',
             '// 64-bit layout numbers only; LLVM field types are defined by CGType.',
             '// LLVM source: ' + pin('llvm_pin.env', 'LLVM_SHA'),
             '// Runtime source: ' + pin('runtime_pin.env', 'RUNTIME_REF'),
             '// Header sha256: ' + hashlib.sha256(header).hexdigest(),
             'package cjcj::codegen', '', 'public class RuntimeLayout {']
    for name in GLOBALS:
        lines.append(f'    public static let {name}: UInt64 = {values[None, name]}u64')
    lines += ['    public static let ArrayLengthSize: UInt64 = ArrayHeaderSize - ArrayLengthOffset',
              '}', '', 'public class TypeInfoLayout {',
              f'    public static let FieldCount: Int64 = {len(FIELDS)}']
    for field in FIELDS:
        for suffix in ('Index', 'Offset'):
            name = field + suffix
            ty, literal = ('Int64', '') if suffix == 'Index' else ('UInt64', 'u64')
            lines.append(f'    public static let {name}: {ty} = {values["TypeInfo", name]}{literal}')
    return '\n'.join(lines + ['}', ''])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--header', required=True, type=Path)
    parser.add_argument('--runtime-root', required=True, type=Path)
    parser.add_argument('--output', type=Path, default=ROOT / 'packages/codegen/src/RuntimeLayout.cj')
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--check', action='store_true')
    mode.add_argument('--write', action='store_true')
    args = parser.parse_args()
    # Runtime owns assertion extraction and header comparison, including constants
    # not consumed by the frontend. Do not maintain a second assertion parser.
    subprocess.run([sys.executable, str(args.runtime_root / 'runtime/tools/generate-runtime-layout.py'),
                    '--header', str(args.header)], check=True)
    expected = render(args.header.read_bytes())
    if args.check:
        if not args.output.exists() or args.output.read_text() != expected:
            raise ValueError(f'CODEGEN_LAYOUT=STALE generated source differs: {args.output}')
        print('CODEGEN_LAYOUT=OK generated source matches validated runtime/LLVM header')
    else:
        args.output.write_text(expected)


if __name__ == '__main__':
    try:
        main()
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
