[package]
  cjc-version = "1.1.0"
  name = "lex"
  organization = "cangjie_compiler"
  description = "Self-hosted Cangjie compiler Lex module scaffold"
  version = "0.1.0"
  target-dir = ""
  script-dir = ""
  src-dir = "src"
  output-type = "static"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]
  "cangjie_compiler::basic" = { path = "../basic" }
